version: "3.9"
services:
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - '5432:5432'
    networks:
      - phonenet
  api:
    build: ./api
    image: apiimage
    restart: always
    environment:
      MAIN_MASTER_URL: db
    ports:
      - '5000:5000'
    depends_on:
      - db
    networks:
      - phonenet
  portal:
    build: ./portal
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - api
    networks:
      - phonenet
networks:
  phonenet:
